### ISSUE TITLE
Error: Cannot update oldest data, last time=1658933400, new time=1658899800

### ISSUE THREAD

**Issue by VishwasNagarkar** [tradingview/lightweight-charts-android#121]
Hi Team, 
 we are getting below crash in crashlytics

log:- 
Fatal Exception: java.lang.IllegalStateException: Error: Cannot update oldest data, last time=1658933400, new time=1658899800
       at jsCode.DataLayer._internal_updateSeriesData(DataLayer.java:10676)
       at jsCode.ChartApi._internal_updateData(ChartApi.java:11637)
       at jsCode.SeriesApi.update(SeriesApi.java:11002)
       at jsCode.Object.<anonymous>(Object.java:12344)
       at jsCode.SeriesInstanceService._findSeries(SeriesInstanceService.java:12217)
       at jsCode.Object.functionRef(Object.java:12174)
       at jsCode.FunctionManager.call(FunctionManager.java:11809)
       at jsCode.MessagePort.port.onmessage(port.java:13127)

we are unable to reproduce it at our end could you please investigate it and provide us with further solution

**Comment by makedonsky94** [comment]
Hi! This error occurring when you trying to insert or update bar which is older than latest bar in series.
